
nginx:
    image: nginx:latest
    container_name: use_a-frame
    ports: 
        - "80:80"
    volumes:
        - ./index.html:/usr/share/nginx/html/index.html
        - ./html:/usr/share/nginx/html/html